= Mejores prácticas para etiquetas en Loki

Loki está en desarrollo activo y trabajamos constantemente para mejorar el rendimiento. Pero estas son algunas de las mejores prácticas más actuales para etiquetas que le brindarán la mejor experiencia con Loki.

== Las etiquetas estáticas son buenas

Cosas como host, aplicación y entorno son excelentes etiquetas. Serán limitados para un sistema/aplicación dado y tendrán valores limitados. Use etiquetas estáticas para facilitar la consulta de sus registros en un sentido lógico (por ejemplo, muéstreme todos los registros para una aplicación determinada y un entorno específico, o muéstreme todos los registros para todas las aplicaciones en un host específico).

== Utilizar etiquetas dinámicas con moderación

Demasiadas combinaciones de valores de etiquetas dan lugar a demasiados flujos. Las sanciones por eso en Loki son un índice grande y pequeñas porciones en el almacén, lo que a su vez puede reducir el rendimiento.

Para evitar esos problemas, no agregue una etiqueta a algo hasta que sepa que lo necesita. Utilice expresiones de filtro ( |= “text”, |~ “regex”, …) y aplique fuerza bruta a esos registros. Funciona y es rápido.

Desde el principio, hemos establecido una etiqueta dinámicamente utilizando fuentes de información Promtail para `level`. Esto nos pareció intuitivo, ya que a menudo solo queríamos mostrar registros para `level=”error”`; sin embargo, estamos reevaluando esto ahora como si escribiera una consulta. `{app=”loki”} |= “level=error”` está demostrando ser tan rápido para muchas de nuestras aplicaciones como `{app=”loki”,level=”error”}`.

Esto puede parecer sorprendente, pero si las aplicaciones tienen un volumen medio a bajo, esa etiqueta hace que los registros de una aplicación se dividan en hasta cinco flujos, lo que significa que se almacenan 5 veces más fragmentos. Y la carga de fragmentos tiene una sobrecarga asociada. Imagínese ahora si esa consulta fuera `{app=”loki”,level!=”debug”}`. Eso tendrá que cargar *muchos* más fragmentos que `{app=”loki”} != “level=debug”`.

Anteriormente, mencionamos no agregar etiquetas hasta que las _necesitara_, entonces, ¿cuándo _necesitaría_ etiquetas? Un poco más abajo hay una sección sobre `chunk_target_size`. Si establece esto en 1MB (lo cual es razonable), esto intentará cortar fragmentos con un tamaño comprimido de 1MB, que es aproximadamente 5MB de registros sin comprimir (puede ser hasta 10MB según la compresión). Si sus registros tienen suficiente volumen para escribir 5MB en menos tiempo que `max_chunk_age`, o *muchos* fragmentos en ese período de tiempo, es posible que desee considerar dividirlos en flujos separados con una etiqueta dinámica.

Lo que desea evitar es dividir un archivo de registro en flujos, lo que da como resultado que los fragmentos se vacíen porque el flujo está inactivo o alcanza la edad máxima antes de llenarse. A partir de https://grafana.com/blog/2020/04/01/loki-v1.4.0-released-with-query-statistics-and-up-to-300x-regex-optimization/[Loki 1.4.0], hay una métrica que puede ayudarlo a comprender por qué los fragmentos se vacían `sum by (reason) (rate(loki_ingester_chunks_flushed_total{cluster="dev"}[1m]))`.

No es fundamental que todos los fragmentos estén llenos cuando se vacían, pero mejorará muchos aspectos de la operación. Como tal, nuestra guía actual aquí es evitar las etiquetas dinámicas tanto como sea posible y, en cambio, favorecer las expresiones de filtro. Por ejemplo, no agregue una etiqueta dinámica `level`, simplemente `|= “level=debug”` en su lugar.

== Los valores de las etiquetas siempre deben estar limitados

Si está configurando etiquetas dinámicamente, nunca use una etiqueta que pueda tener valores ilimitados o infinitos. Esto siempre resultará en grandes problemas para Loki.

Trate de mantener los valores delimitados a un conjunto lo más pequeño posible. No tenemos una guía perfecta sobre lo que puede manejar Loki, pero piense en dígitos de un solo dígito, o tal vez decenas de valores para una etiqueta dinámica. Esto es menos crítico para las etiquetas estáticas. Por ejemplo, si tiene 1000 hosts en su entorno, estará bien tener una etiqueta de host con 1000 valores.

== Tenga en cuenta las etiquetas dinámicas aplicadas por los clientes

Loki tiene varias opciones de cliente: https://github.com/grafana/loki/tree/master/docs/sources/clients/promtail[Promtail] (que también admite la ingestión de diarios de systemd y la ingesta de syslog basada en TCP), https://github.com/grafana/loki/tree/master/fluentd/fluent-plugin-grafana-loki[Fluentd], https://github.com/grafana/loki/tree/master/cmd/fluent-bit[Fluent Bit], un https://grafana.com/blog/2019/07/15/lokis-path-to-ga-docker-logging-driver-plugin-support-for-systemd/[complemento de Docker] y más.

Cada uno de estos viene con formas de configurar qué etiquetas se aplican para crear flujos de registro. Pero tenga en cuenta qué etiquetas dinámicas se pueden aplicar. Use la API de la serie Loki para tener una idea de cómo se ven sus flujos de registro y ver si puede utilizar formas de reducir los flujos y la cardinalidad. La información de la serie se puede consultar a través de la xref:api/api.adoc#series[API de la Serie], o puede utilizar xref:comenzando/logcli.adoc[logcli].

En Loki 1.6.0 y posteriores, el comando de la serie logcli agregó el indicador `--analyze-labels` específicamente para depurar etiquetas de alta cardinalidad:

----
Total Streams:  25017
Unique Labels:  8

Label Name  Unique Values  Found In Streams
requestId   24653          24979
logStream   1194           25016
logGroup    140            25016
accountId   13             25016
logger      1              25017
source      1              25016
transport   1              25017
format      1              25017
----

En este ejemplo, puede ver que la etiqueta `requestId` tenía 24653 valores diferentes de 24979 secuencias en las que se encontró, ¡esto es malo!

Este es un ejemplo perfecto de algo que no debería ser una etiqueta, `requestId` debería eliminarse como una etiqueta y, en su lugar, deberían usarse expresiones de filtro para consultar registros para un `requestId` específico. Por ejemplo, si `requestId` se encuentra en la línea de registro como un par clave=valor, puede escribir una consulta como esta: `{logGroup="group1"} |= "requestId=32422355"`

== Configurar el almacenamiento en caché

Loki puede almacenar datos en caché en muchos niveles, lo que puede mejorar drásticamente el rendimiento. Los detalles de esto estarán en una publicación futura.

== Los registros deben estar en orden de tiempo creciente por flujo

Un problema que muchas personas tienen con Loki es que su cliente recibe errores por entradas de registro fuera de orden. Esto sucede debido a esta regla estricta y rápida dentro de Loki:

* Para cualquier flujo de registro único, los registros siempre deben enviarse en orden de tiempo creciente. Si se recibe un registro con una marca de tiempo más antigua que el registro más reciente recibido para ese flujo, ese registro se eliminará.

Hay algunas cosas para analizar de esa declaración. La primera es que esta restricción es por flujo. Veamos un ejemplo:

----
{job=”syslog”} 00:00:00 i’m a syslog!
{job=”syslog”} 00:00:01 i’m a syslog!
----

Si Loki recibiera estas dos líneas que son para el mismo flujo, todo estaría bien. Pero, ¿qué pasa con este caso?

----
{job=”syslog”} 00:00:00 i’m a syslog!
{job=”syslog”} 00:00:02 i’m a syslog!
{job=”syslog”} 00:00:01 i’m a syslog!  <- Rejected out of order!
----

¿Qué podemos hacer al respecto? ¿Y si esto se debiera a que las fuentes de estos registros eran sistemas diferentes? Podemos resolver esto con una etiqueta adicional que es única por sistema:

----
{job=”syslog”, instance=”host1”} 00:00:00 i’m a syslog!
{job=”syslog”, instance=”host1”} 00:00:02 i’m a syslog!
{job=”syslog”, instance=”host2”} 00:00:01 i’m a syslog!  <- Accepted, this is a new stream!
{job=”syslog”, instance=”host1”} 00:00:03 i’m a syslog!  <- Accepted, still in order for stream 1
{job=”syslog”, instance=”host2”} 00:00:02 i’m a syslog!  <- Accepted, still in order for stream 2
----

Pero, ¿qué pasa si la propia aplicación genera registros que no funcionan? Bueno, me temo que esto es un problema. Si extrae la marca de tiempo de la línea de registro con algo como xref:clientes/promtail/etapas/marca-de-tiempo.adoc[la etapa de fuente de información de promtail], usted podría _no hacer_ esto y dejar que Promtail asigne una marca de tiempo a las líneas de registro. O con suerte, puede solucionarlo en la propia aplicación.

¡Pero quiero que Loki arregle esto! ¿Por qué no puedes almacenar en búfer los flujos y reordenarlos por mí? Para ser honesto, porque esto agregaría mucha sobrecarga de memoria y complicación a Loki, y como ha sido un hilo común en esta publicación, queremos que Loki sea simple y rentable. Idealmente, querríamos mejorar a nuestros clientes para que realicen un almacenamiento y una clasificación básicos, ya que este parece un mejor lugar para resolver este problema.

También vale la pena señalar que la naturaleza de procesamiento por lotes de la _API push_ de Loki puede llevar a que se reciban algunos casos de errores fuera de orden, que en realidad son falsos positivos. (Quizás un lote tuvo éxito parcialmente y estuvo presente; o cualquier cosa que haya tenido éxito anteriormente devolvería una entrada fuera de orden; o se aceptaría algo nuevo).

== Utilizar `chunk_target_size`

Esto se agregó anteriormente en la versión de https://grafana.com/blog/2020/01/22/loki-1.3.0-released/[Loki v1.3.0] y hemos estado experimentando con ello durante varios meses. Tenemos `chunk_target_size: 1536000` en todos nuestros entornos ahora. Esto le indica a Loki que intente llenar todos los fragmentos hasta un tamaño _comprimido_ objetivo de 1,5MB. Estos fragmentos más grandes son más eficientes para que Loki los procese.

Un par de otras variables de configuración afectan la capacidad de un fragmento. Loki tiene un `max_chunk_age` predeterminado de 1h y `chunk_idle_period` de 30m para limitar la cantidad de memoria utilizada, así como la exposición de registros perdidos si el proceso falla.

Dependiendo de la compresión utilizada (hemos estado usando snappy, que tiene menos compresibilidad pero un rendimiento más rápido), necesita 5-10x o 7,5-10MB de datos de registro sin procesar para llenar un fragmento de 1,5MB. Recordando que un fragmento es por flujo, en cuantos más flujos divida sus archivos de registro, más fragmentos se quedarán en la memoria y mayor será la probabilidad de que se vacíen al alcanzar uno de los tiempos de espera mencionados anteriormente antes de que se llenen.

Muchos fragmentos pequeños sin relleno son actualmente kriptonita para Loki. Siempre estamos trabajando para mejorar esto y podemos considerar un compactador para mejorarlo en algunas situaciones. Pero, en general, la guía debería ser la misma: ¡haga todo lo posible para llenar los fragmentos!

Si tiene una aplicación que puede registrar lo suficientemente rápido como para llenar estos fragmentos rápidamente (mucho menos que `max_chunk_age`), entonces es más razonable usar etiquetas dinámicas para dividirlo en flujos separados.

== Utilizar `-print-config-stderr` o `-log-config-reverse-order`

A partir de la versión 1.6.0, Loki y Promtail tienen indicadores que volcarán todo el objeto de configuración en stderr, o el archivo de registro, cuando se inicien.

`-print-config-stderr` es bueno cuando se ejecuta loki directamente, p. ej. `./loki`, ya que puede obtener una salida rápida de toda la configuración de Loki.

`-log-config-reverse-order` es el indicador con el que ejecutamos Loki en todos nuestros entornos, las entradas de configuración se invierten para que el orden de las configuraciones se lea correctamente de arriba a abajo cuando se ve en Explorar en Grafana.