= Cómo obtener archivos binarios de IoTDB

IoTDB le proporciona tres métodos de instalación, puede consultar las siguientes sugerencias, elija uno de ellos:

. Instalación desde código fuente. Si necesita modificar el código usted mismo, puede utilizar este método.

. Instalación desde archivos binarios. Descargue los archivos binarios del sitio web oficial. Este es el método recomendado, en el que obtendrá un paquete binario liberado que está listo para usar.

. Usando Docker: la ruta al archivo docker es https://github.com/apache/iotdb/blob/master/docker/Dockerfile

== Prerequisitos

Para usar IoTDB, debe tener:

. Java >= 1.8 (Asegúrese de que se haya establecido la ruta del entorno)

. Maven >= 3.6 (Opcional)

. Establezca el número máximo de archivos abiertos como 65535 para evitar el problema de "demasiados archivos abiertos".

[NOTE]
----
Si no tiene maven instalado, debe reemplazar 'mvn' en los siguientes comandos con 'mvnw.sh' o 'mvnw.cmd'.
----

== Instalación desde archivos binarios

Puede descargar el archivo binario desde: https://iotdb.apache.org/Download/[Página de descarga]

== Instalación desde el código fuente

Puede obtener el código fuente publicado en https://iotdb.apache.org/Download/, o desde el repositorio de git https://github.com/apache/iotdb/tree/master.

Puede descargar el código fuente desde:

[source]
----
git clone https://github.com/apache/iotdb.git
----

Bajo la ruta raíz de iotdb:

[source]
----
> mvn clean package -DskipTests
----

Luego, la versión binaria (incluidos el servidor y el cliente) se puede encontrar en distribution *distribution/target/apache-iotdb-{project.version}-bin.zip*

[NOTE]
----
Los directorios "thrift/target/generated-sources/thrift" y "antlr/target/generated-sources/antlr4" deben agregarse a las raíces de las fuentes para evitar errores de compilación en IDE.
----

Si desea construir el servidor IoTDB, puede ejecutar el siguiente comando en la ruta raíz de iotdb:

[source]
----
> mvn clean package -pl server -am -DskipTests
----

Después de la compilación, el servidor IoTDB estará en la carpeta "server/target/iotdb-server-{project.version}".

== Instalación por Docker (Dockerfile)

Apache IoTDB 'La imagen de Docker se publica en https://hub.docker.com/r/apache/iotdb, usando `docker pull apache/iotdb:latest` puede obtener la última imagen de docker.

Los usuarios también pueden crear una imagen de Docker por sí mismos.

Ahora se ha escrito un Dockerfile en docker/src/main/Dockerfile.

. Puede crear una imagen de Docker de la siguiente manera:

[source]
----
$ docker build -t iotdb:base git://github.com/apache/iotdb#master:docker
----

O:

[source]
----
$ git clone https://github.com/apache/iotdb
$ cd iotdb
$ cd docker
$ docker build -t iotdb:base .
----

Una vez que la imagen de docker se ha creado localmente (la etiqueta es iotdb:base en este ejemplo), ¡casi ha terminado!

. Crear un volumen de ventana acoplable para archivos de datos y registros:

[source]
----
$ docker volume crear mydata
$ docker volume crear mylogs
----

. Ejecutar un contenedor docker:
[source]
----
$ docker run -p 6667:6667 -v mydata:/iotdb/data -v mylogs:/iotdb/logs -d iotdb:base /iotdb/bin/start-server.sh
----

Si tiene éxito, puede ejecutar `docker ps` y obtener algo como lo siguiente:

[source]
----
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
2a68b6944cb5        iotdb:base          "/iotdb/bin/start-se…"   4 minutes ago       Up 5 minutes        0.0.0.0:6667->6667/tcp              laughing_meitner
----

Puede usar el comando anterior para obtener el ID del contenedor:

[source]
----
$ docker container ls
----

Suponga que el ID es <C_ID>.

Y obtenga la IP de docker mediante:

[source]
----
$ docker inspect --format='{{.NetworkSettings.IPAddress}}' <C_ID>
----

Suponga que la IP es <C_IP>.

. Si solo quiere probar usando iotdb-cli, puede:

[source]
----
$ docker exec -it /bin/bash  <C_ID>
$ (now you have enter the container): /cli/sbin/start-cli.sh -h localhost -p 6667 -u root -pw root
----

O ejecute un nuevo contenedor docker como cliente:

[source]
----
$ docker run -it iotdb:base /cli/sbin/start-cli.sh -h <C_IP> -p 6667 -u root -pw root
----

O, si tiene un iotdb-cli localmente (por ejemplo, ha compilado el código fuente por el `mvn package`), y suponga que su work_dir es cli/bin, entonces puede ejecutar:

[source]
----
$ start-cli.sh -h localhost -p 6667 -u root -pw root
----

. Si desea escribir códigos para insertar datos y consultar datos, agregue la siguiente dependencia:

[source]
----
        <dependency>
            <groupId>org.apache.iotdb</groupId>
            <artifactId>iotdb-jdbc</artifactId>
            <version>0.10.0</version>
        </dependency>
----

Se pueden encontrar algunos ejemplos sobre cómo usar IoTDB con IoTDB-JDBC en: https://github.com/apache/iotdb/tree/master/example/jdbc/src/main/java/org/apache/iotdb

. ¡Ahora disfrútelo!